# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45a8cc2a2e3fdda62085d886f1b8ca61108e57f79bec5f000f797a3868d667911142b30e896bf2557b5be80bc23a9442bc4b8f849138426228792446f0561e96

test:
  secret_key_base: 032021d2ee7b2426b8e1c38f4bd75e97a1793def940904596789ce755ca4649f337d930a81f1ae10d1d3a0da2e815e8723ef2c91d9f1e40a53bccfe71a35ab68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
